### ISSUE TITLE
Future of Wear app?

### ISSUE THREAD

**Issue by mwhdc** [patzly/tack-android#24]
I installed the Wear app while it was available and love the UI, though the actual timekeeping feels wonky which I assume is an issue with the OS. Do you plan to publish a Wear build of your 4.x codebase or is Wear OS not sufficiently reliable/robust for this sort of app? (Thank you for the Android app which is also fantastic.)

**Comment by patzly** [comment]
Hey thank you so much for the issue! You can look forward to a completely rewritten Wear OS app for Tack in a few days! I'm currently very busy with rewriting the entire app in Kotlin and Jetpack Compose with Material 3, the most modern standard for Wear OS (and I had to learn Kotlin and Compose for this first).
The old app was developed for a too old version of Wear OS because I haven't updated it since 2021 and the audio algorithm was based on a method that didn't write a continuous stream to audio output which caused problems since Android 11 changed something internally I think.
I had to take it down because Google Play prevented me from updating the phone app to v4.0 because the old Wear OS created policy issues.
One thing you will miss in the new version is the tempo wheel. Sadly it's not possible anymore to turn off the swipe-to-dismiss gesture (to close an app) temporarily while rotating, so I had to move setting the tempo to an extra screen + swiping up and down on the main screen.
Hope you like the news!

**Comment by mwhdc** [comment]
That's great! Looking forward to the new build. That makes sense about the old audio algorithm, it sounded like the audible beat was constantly fluctuating. I will miss the tempo wheel (it works well on Galaxy Watch 6) but glad that it remains in the Android app. Thanks again for the gorgeous design and Wear support, the haptic beat on the watch has been really useful. Closing the issue.

**Comment by patzly** [comment]
Finally I was able to finish the first Wear OS release of the rewrite and Google approved it yesterday, so you can install the Wear OS version right now! Hope you like it and if you find any issue that is not on the list please open a new one :)

**Comment by mwhdc** [comment]
New Wear build is awesome! RIP tempo wheel but the +/- increments are a great replacement & possibly more practical. Beats & subdivisions feel spot on. Amazing to have this functionality on your wrist. Thanks again for all the work on this & publishing it.

**Comment by patzly** [comment]
Glad you like it so much! Yes the lost tempo wheel is sad but I think the space is better used by the other controls, a wheel just needs space. Also glad that you like the new emphasis page!
