### ISSUE TITLE
Application crashes when opening from app info screen 

### ISSUE THREAD

**Issue by pikumar98** [patzly/tack-android#37]
Application crashes when opening after 4.4.0 update.

https://github.com/user-attachments/assets/6f5df6fe-5dda-4665-a24c-4abc84f0fd07

**Comment by ZmaZes** [comment]
I also noticed this. I took a look and it seems like the MainActivity Activity of the app is private for some reason. Apps try to launch it but the only activity that is public is the SplashActivity, which is not the intended activity to launch the app with, and therefore it crashes. It is able to open from the launcher because it has access to these private activities but nothing else does for some reason.

**Comment by patzly** [comment]
@pikumar98 Thanks for the report! So the app only crashes when opened through the app info, am I right? Or why does it open normally in some parts of your recording?

@ZmaZes This is a special mechanism I have written for making the splash screen work equally on newer and older devices in my apps. SplashActivity extends MainActivity, and on newer devices `super.onCreate()` is called so SplashActivity is transformed into MainActivity internally (`super.onCreate()` calls `onCreate()` from the extended activity). On older devices the splash screen is shown and then MainActivity is started separately instead, so SplashActivity is the only activity which is ever opened by the system.

With a high possibility the crash is caused by the recently added line `assert startTime != null` because I didn't know that the animation start time is sometimes not provided.

**Could you please check if the following zipped test release works for you? Could you also please make the same screen recording again if it works (start from app info and recents screen multiple times)? I need to check if my fix uses the correct default start time for the splash animation to look good. Thanks a lot!**
[Tack-Android-v4.4.1.apk.zip](https://github.com/user-attachments/files/17084444/Tack-Android-v4.4.1.apk.zip)

**Comment by pikumar98** [comment]
Yes @patzly, the app crashes only when opened from the app info screen.
The app opens fine when opened from the app drawer or the recent apps screen. Rhis behaviour is noted in the play store app as well.

In the previous recording, the app opens normally because it was opened from the recent apps screen.

Recording from 4.4.1 - https://we.tl/t-IlZdLfID3f

In version 4.4.1, the splash screen is not shown when opened from app info screen.

**Comment by patzly** [comment]
I've just released [v4.4.1](https://github.com/patzly/tack-android/releases/tag/v4.4.1) with the fix included! Thanks again for reporting!
